version: '2'
services:
    memcache:
        image: memcached:1.4.35-alpine
        restart: always
    default:
        image: registry.aliyuncs.com/syncxplus/php:7.1.3
        restart: always
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        links:
            - memcache:memcache
        depends_on:
            - memcache
